baseURL = "https://apollokwok.github.io/ITWorks/"
languageCode = "en-us"
title = "ITWorks"
theme = ["hugo-video", "hugo-book"]

disableFingerprinting = true
pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# Needed for mermaid shortcode
[markup.tableOfContents]
startLevel = 1
endLevel = 11

[taxonomies]
tag = "tags"

[menu]

[[menu.after]]
name = "About"
url = "https://shawxingkwok.github.io/TracerTutorial/"
weight = 1
#

[[menu.after]]
identifier = "my-after-menu"
name = "My After Menu"
url = "https://shawxingkwok.github.io/TracerTutorial/"
weight = 2
pre = "<img src='/github.png' alt='Menu Icon' style='height: 20px; width: auto; vertical-align: middle; margin-right: 5px;' />"

#
[[menu.after]]
name = "Email"
url = "https://shawxingkwok.github.io/TracerTutorial/"
weight = 3

[params]
BookRepo = 'https://github.com/ShawxingKwok/ITWorks'
BookEditPath = 'blob/main'