baseURL = "https://shawxingkwok.github.io/ITWorks/"
languageCode = "en-us"
title = "ITWorks"
theme = ["hugo-video", "hugo-book"]

disableFingerprinting = true
pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# Needed for mermaid shortcode
[markup.tableOfContents]
startLevel = 1
endLevel = 11

[taxonomies]
tag = "tags"

[menu]
[[menu.after]]
name = "Github"
url = "https://github.com/ShawxingKwok"
weight = 3

[[menu.after]]
name = "Email"
url = "mailto:ShawxingKwok@126.com"
weight = 4

[params]
BookRepo = 'https://github.com/ShawxingKwok/ITWorks'
BookEditPath = 'blob/main'