baseURL = "https://apollokwok.github.io/ITWorks/"
languageCode = "en-us"
title = "ITWorks"
theme = ["hugo-video", "hugo-book"]

disableFingerprinting = true
pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# Needed for mermaid shortcode
[markup.tableOfContents]
startLevel = 1
endLevel = 11

[taxonomies]
tag = "tags"

[menu]
[[menu.after]]
name = "Tracer"
url = "https://shawxingkwok.github.io/TracerTutorial/"
weight = 10

[[menu.after]]
name = "-----------------"
url = ""
weight = 20

[[menu.after]]
name = "About me"
pageRef = './docs/_index.md'
url = "https://shawxingkwok.github.io/ITWorks/docs/"
weight = 30

[[menu.after]]
name = "Github profile"
url = "https://github.com/ShawxingKwok/"
weight = 40

[params]
BookRepo = 'https://github.com/ShawxingKwok/ITWorks'
BookEditPath = 'blob/main'